<?php

namespace Database\Seeders;

use App\Models\LokasiPenularanMaster;
use Illuminate\Database\Seeder;

class LokasiPenularanSeeder extends Seeder
{
    public function run(): void
    {
        $sekolah = [
            'TK AISYAH BUSTANUL ATHFAL ABA) 8',
            'TK CENDRAWASIH',
            'TK IT BAITURRAHMAN',
            'TK IT YABIS',
            'TK NEGERI 1 (PEMBINA)',
            'TK NEGERI 2 BONTANG',
            'TK NEGERI 3 BONTANG',
            'TK YPPI',
            'RA/BA/TA AS SALAM',
            'RA/BA/TA HIDAYATUL AMALIA',
            'RA/BA/TA QURRATA A`YUN',
            'RA/BA/TA DDI',
            'RA/BA/TA INSAN MULIA',
            'RA/BA/TA NURUL BAHRI',
            'RA/BA/TA TABLIGH YAJUBRIS',
            'RA/BA/TA AL AMIN MUHAMMAD',
            'RA/BA/TA AL IKHLAS',
            'RA/BA/TA BAITUL MU TADIL',
            'KB CENDANA',
            'KB AL KAUTSAR',
            'KB IHYAUSSUNNAH',
            'KB GO PKB',
            'KB AL-IKHWAN',
            'KB QURROTA A YUN',
            'KB YPPI',
            'KB TERAPUNG DAERAH TERPENCIL',
            'KB KASIH BUNDA I',
            'KB ISLAM MIFTAHUL HUDA',
            'KB ISLAM HIDAYATULLAH',
            'KB KARYA MANDIRI',
            'KB AL HIKMAH',
            'KB FLAMBOYAN',
            'KB KARTIKA PURI II',
            'KB Kemala Bhayangkari',
            'KB KREATIF',
            'KB MADANI',
            'KASIH BUNDA II',
            'KB PERINTIS',
            'KB NICE KIDS KHATULISTIWA',
            'KB ISLAM DARUSALLAM',
            'KB PALOS MANJU',
            'KB SANTA THERESIA',
            'KB IT AL-JIHAD',
            'KB KUNCUP MELATI',
            'KB IT BAITURRAHMAN',
            'TPA AL-KAUTSAR',
            'TPA MUHAFADZATUL ATHFAL',
            'TPA RAUDHATUN NI MAH',
            'TPA ASH SHIBYAN',
            'TPA CERIA',
            'TK AISYIYAH BUSTANUL ATHFAL ( ABA) VI',
            'TK AISYIYAH BUSTANUL ATHFAL V',
            'TK ISLAM Al FALAH',
            'TK IT IHYAUSSUNNAH',
            'TK ISLAM KARTINI',
            'TK AISYIYAH BUSTANUL ATHFAL (ABA) VII',
            'TK SUMBER KASIH',
            'TK ISLAM NURUL IMAN',
            'TK AL IKHWAN',
            'TK IT QURROTA A YUN',
            'TK YAPIM',
            'TK AISYIYAH BUSTANUL ATHFAL (ABA) I',
            'TK AL-HUDA',
            'TK AISYIYAH BUSTANUL ATHFAL (ABA) III',
            'TK AISYIYAH BUSTANUL ATHFAL (ABA) II',
            'TK IT MIFTAHUL HUDA',
            'TK AL HIDAYAH',
            'TK AL HIKMAH',
            'TK ISLAM HIDAYATULLAH',
            'TK KARTIKA V-10',
            'TK NOMENSEN',
            'TK BETHLEHEM',
            'TK Kemala Bhayangkari',
            'TK TUNAS MEKAR',
            'TK IMANUEL',
            'TK ISLAM NURUL FATAH',
            'TK ISLAM NURUL MUTTAQIN',
            'TK KREATIF',
            'TK PLUS AL. MUHAJIRIN',
            'TK DARUL ULUM',
            'TK MADANI BONTANG',
            'TK PERINTIS',
            'TK SANTA THERESIA',
            'TK AISYIYAH BUSTANUL ATHFAL IV',
            'TK ISLAM AL JIHAD',
            'TK GALILEA',
            'TK ISLAM ASY SYIFA',
            'TK KUNCUP MELATI',
            'TK AL IHSAN',
            'TK YAYASAN PUPUK KALTIM',
            'TK ISLAM AL-ASKARI',
            'KB TUDAI',
            'TK AL-KAUTSAR',
            'TPA BAITURRAHMAN',
            'TPA YABIS',
            'TPA SANUR BADAR',
            'KB BINTANG HARAPAN',
            'TPA RUMAH PELANGI',
            'TPA HIDAYATULLAH',
            'SPS ANYELIR XIII',
            'SPS ANYELIR VIII',
            'SPS POS PAUD ANYELIR I',
            'SPS POS PAUD ANYELIR III',
            'SPS ANYELIR IV',
            'SPS ANYELIR V',
            'SPS POS PAUD ANYELIR VI',
            'SPS ANGGREK II',
            'SPS ANGGREK III',
            'SPS POS PAUD ANGGREK V',
            'SPS ANGGREK BULAN 1',
            'SPS ANGGREK BULAN 3',
            'SPS ANGGREK BULAN 4',
            'SPS ANGGREK BULAN 7',
            'SPS ANGGREK BULAN 2',
            'SPS ANGGREK MERAH',
            'TPA KUNCUP MELATI',
            'KB KASIH BUNDA IV',
            'KB KASIH BUNDA III',
            'SPS POS PAUD ANYELIR VII',
            'KB ZAKA QURBA',
            'TPA NURUL FATAH',
            'KB ISLAM NURUL FATAH',
            'TK GO PKB',
            'SPS ANGGREK VII',
            'SPS KEMALA BHAYANGKARI',
            'SPS ANYELIR XII',
            'TPA ISLAM AL-FALAH',
            'SPS PASIR PUTIH 1',
            'SPS PASIR PUTIH 3',
            'KB AL IHSAN',
            'KB YPK',
            'KB ABA 8',
            'TPA TAAM AS SAKINAH',
            'SPS NUR-HIKMAH',
            'SPS ANYELIR X',
            'SPS ANGGREK I',
            'SPS AL-IKHLAS',
            'SPS ANGGREK IV',
            'SPS POS PAUD ANYELIR XI',
            'SPS POS PAUD ANYELIR IX',
            'SPS POS PAUD ANYELIR II',
            'KB NICE KIDS GUNTUNG',
            'SPS ANGGREK VI',
            'SPS CENDRAWASIH',
            'TPA AMALIA',
            'SPS A.A VAN DE LOOSDRECHT',
            'SPS PKBM MELATI',
            'As Sakinah',
            'TPA SOLAFIDE',
            'SPS PASIR PUTIH 4',
            'SPS NUR AFFIFAH',
            'TK NICE KIDS GUNTUNG',
            'TK KATOLIK SANTO YOSEF',
            'TPA CENDRAWASIH',
            'KB IT YABIS',
            'KB EFATA',
            'TK ISLAM KREATIF SALSABILA BONTANG',
            'TPA ISLAM TERPADU QURROTAAYUN',
            'TPA FAMUS KIDS',
            'TK DARUL FURQON',
        ];

        foreach ($sekolah as $nama) {
            LokasiPenularanMaster::updateOrCreate(
                ['nama' => $nama, 'kategori' => 'Sekolah'],
                ['is_custom' => false]
            );
        }

        $this->command->info('LokasiPenularanSeeder: ' . count($sekolah) . ' data sekolah berhasil di-seed.');
    }
}
